name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rails-version: [6, 7]
    env:
      BUNDLE_GEMFILE: gemfiles/rails${{ matrix.rails-version }}.gemfile
      RSPEC_FULL_BACKTRACE: yes
      CS_IDP_CLIENT_SECRET: ${{ secrets.CS_IDP_CLIENT_SECRET }}
      CS_WORKSPACE: ${{ secrets.CS_WORKSPACE }}
      CS_KMS_KEY_ARN: ${{ secrets.CS_KMS_KEY_ARN }}
      CS_NAMING_KEY:  ${{ secrets.CS_NAMING_KEY }}
      RAILS_VERSION: ${{ matrix.rails-version }}
      ACTIVE_STASH_TEST_COLLECTION_PREFIX: rails_${{ matrix.rails-version }}
      PGDATABASE: activestash_test_rails_${{ matrix.rails-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
          bundler-cache: true
      - uses: ankane/setup-postgres@v1
        with:
          database: activestash_test_rails_${{ matrix.rails-version }}
      # Ensures that the database is in a clean state before any test runs.
      - run: psql -d activestash_test_rails_${{ matrix.rails-version }} -c 'DROP SCHEMA public CASCADE; CREATE SCHEMA public;'
      - run: bundle exec rake spec
