name: "ActiveStash: Test"
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  run-specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rails-version: [6, 7]
        ruby-version: [2.7, 3.0, 3.1]
    env:
      BUNDLE_GEMFILE: gemfiles/rails${{ matrix.rails-version }}.gemfile
      RSPEC_FULL_BACKTRACE: yes
      CS_IDP_CLIENT_SECRET: ${{ secrets.CS_IDP_CLIENT_SECRET }}
      CS_WORKSPACE: ${{ secrets.CS_WORKSPACE }}
      CS_KMS_KEY_ARN: ${{ secrets.CS_KMS_KEY_ARN }}
      CS_NAMING_KEY:  ${{ secrets.CS_NAMING_KEY }}
      RAILS_VERSION: ${{ matrix.rails-version }}
      ACTIVE_STASH_TEST_COLLECTION_PREFIX: run_${{ github.run_number }}_job_${{ strategy.job-index }}
      PGDATABASE: activestash_test_run_${{ github.run_number }}_job_${{ strategy.job-index }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - uses: ankane/setup-postgres@v1
        with:
          database: ${{ env.PGDATABASE }}
      # Ensures that the database is in a clean state before any test runs.
      - name: "Show unique job ID"
        run: echo ${{ env.ACTIVE_STASH_TEST_COLLECTION_PREFIX }}
      - name: "Clear out database"
        run: psql -d ${{ env.PGDATABASE }} -c 'DROP SCHEMA public CASCADE; CREATE SCHEMA public;'
      - name: Run the tests
        run: bundle exec rake spec
